apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-app-web
  namespace: mall-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-app-web
  template:
    metadata:
      labels:
        app: mall-app-web
    spec:
      imagePullSecrets:
        - name: harbor-secret

      containers:
        - name: mall-app-web
          image: 192.168.0.198/mall/mall-app-web:1.2
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi


          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.5.3
          args:
            - "--nginx.scrape-uri=http://127.0.0.1/nginx_status"
          ports:
            - name: metrics
              containerPort: 9113


---
apiVersion: v1
kind: Service
metadata:
  name: mall-app-web
  namespace: mall-prod
  labels:
    app: mall-app-web
spec:
  type: ClusterIP
  selector:
    app: mall-app-web
  ports:
    - name: http
      port: 80
      targetPort: 80

    - name: metrics
      port: 9113
      targetPort: 9113
