apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: mall-prod
spec:
  selector:
    app: logstash
  ports:

    - name: debug
      port: 4560
      targetPort: 4560

    - name: error
      port: 4561
      targetPort: 4561

    - name: business
      port: 4562
      targetPort: 4562

    - name: record
      port: 4563
      targetPort: 4563

    - name: api
      port: 9600
      targetPort: 9600


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: mall-prod

spec:

  replicas: 1

  selector:
    matchLabels:
      app: logstash


  template:

    metadata:
      labels:
        app: logstash


    spec:

      containers:

      - name: logstash

        image: docker.elastic.co/logstash/logstash:7.17.18


        ports:

        - containerPort: 4560

        - containerPort: 4561

        - containerPort: 4562

        - containerPort: 4563


        volumeMounts:

        - name: config

          mountPath: /usr/share/logstash/pipeline/logstash.conf

          subPath: logstash.conf

        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml

        resources:

          requests:
            memory: 512Mi

          limits:
            memory: 1.5Gi


        startupProbe:
          httpGet:
            path: /
            port: 9600
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 18

        readinessProbe:
          httpGet:
            path: /
            port: 9600
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1

        livenessProbe:
          httpGet:
            path: /
            port: 9600
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3

      volumes:

      - name: config

        configMap:

          name: logstash-config
