grafana:
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  persistence:
    enabled: true
    storageClassName: local-path-retain
    accessModes:
      - ReadWriteOnce
    size: 10Gi


prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi

    retention: 7d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path-retain
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi


alertmanager:
  alertmanagerSpec:
    secrets:
      - qqmail-smtp

    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: qqmail

    alertmanagerConfigNamespaceSelector: {}

    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path-retain
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
