apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ include "mall-admin.fullname" . }}

  labels:
    {{- include "mall-admin.labels" . | nindent 4 }}
    release: monitoring


spec:

  selector:

    matchLabels:

      app: mall-admin


  namespaceSelector:

    matchNames:

      - {{ .Release.Namespace }}


  endpoints:

    - port: http

      path: /actuator/prometheus

      interval: 15s
