apiVersion: v1
kind: Service
metadata:
  name: es
  namespace: mall-prod
spec:
  selector:
    app: es
  ports:
    - name: http
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: mall-prod
spec:
  serviceName: es
  replicas: 1
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: elasticsearch
          image: 192.168.0.198/mall/elasticsearch:7.17.18-ik
          ports:
            - name: http
              containerPort: 9200
          env:
            - name: discovery.type
              value: single-node

            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"

            - name: xpack.security.enabled
              value: "false"

          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 2Gi

          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3


          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data

  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: local-path-retain

        resources:
          requests:
            storage: 20Gi
