apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: elasticsearch-alert-rules
  namespace: mall-prod
  labels:
    release: monitoring
spec:
  groups:
    - name: elasticsearch.rules
      rules:

        - alert: ElasticsearchClusterRed
          expr: |
            elasticsearch_cluster_health_status{color="red"} == 1
          for: 2m
          labels:
            namespace: mall-prod
            severity: critical
          annotations:
            summary: "Elasticsearch cluster is red"
            description: "Elasticsearch cluster {{ $labels.cluster }} is in red state."

        - alert: ElasticsearchJVMHeapUsageHigh
          expr: |
            100 *
            elasticsearch_jvm_memory_used_bytes{area="heap"}
            /
            elasticsearch_jvm_memory_max_bytes{area="heap"}
            > 80
          for: 5m
          labels:
            namespace: mall-prod
            severity: warning
          annotations:
            summary: "Elasticsearch JVM heap usage is high"
            description: "Elasticsearch JVM heap usage has exceeded 80% for 5 minutes."
