apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: redis-alert-rules
  namespace: mall-prod
  labels:
    release: monitoring
spec:
  groups:
    - name: redis.rules
      rules:
        - alert: RedisDown
          expr: redis_up == 0
          for: 2m
          labels:
            namespace: mall-prod
            severity: critical
          annotations:
            summary: "Redis is down"
            description: "Redis exporter cannot connect to the Redis server."
