apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mall-prod
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mall-prod
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:5.0
          ports:
            - name: mongo
              containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: mall-port
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - 'mongo --quiet --eval "db.adminCommand(\"ping\").ok"'
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 24

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'mongo --quiet --eval "db.adminCommand(\"ping\").ok"'
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'mongo --quiet --eval "db.adminCommand(\"ping\").ok"'
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3


          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path-retain
        resources:
          requests:
            storage: 10Gi
