apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-exporter
  namespace: mall-prod
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: mongodb-exporter
  namespaceSelector:
    matchNames:
      - mall-prod
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
