apiVersion: v1
kind: Service
metadata:
  name: rabbit
  namespace: mall-prod
  labels:
    app: rabbit
spec:
  selector:
    app: rabbit
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
    - name: metrics
      port: 15692
      targetPort: 15692

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
  namespace: mall-prod
spec:
  serviceName: rabbit
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: mall
            - name: RABBITMQ_DEFAULT_PASS
              value: mall
            - name: RABBITMQ_DEFAULT_VHOST
              value: /mall

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          startupProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 24

          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          volumeMounts:
            - name: rabbit-data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbit-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path-retain
        resources:
          requests:
            storage: 5Gi
