apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: mall-prod
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mall-prod
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql
        image: mysql:5.7

        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        startupProbe:
          exec:
            command:
              - sh
              - -c
              - 'mysqladmin ping -h 127.0.0.1 -u root -p"$MYSQL_ROOT_PASSWORD"'
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 24

        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - 'mysqladmin ping -h 127.0.0.1 -u root -p"$MYSQL_ROOT_PASSWORD"'
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1

        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - 'mysqladmin ping -h 127.0.0.1 -u root -p"$MYSQL_ROOT_PASSWORD"'
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3


        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql


  volumeClaimTemplates:
  - metadata:
      name: mysql-data

    spec:
      accessModes:
      - ReadWriteOnce

      storageClassName: local-path-retain

      resources:
        requests:
          storage: 10Gi
