apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mall-prod
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root123"
  MYSQL_DATABASE: "mall"
  MYSQL_USER: "reader"
  MYSQL_PASSWORD: "123456"
